### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by muezis** [boratanrikulu/lirik.app#1]
Please add a player. I learn the language by reading the lyrics, and it is important for me to be able to rewind and pause to listen a particular phrase again.

So far, your app isn't much better than just opening text on genius. But if you make a normal player that can be conveniently controlled, it will be the best that is available at the moment.

**Comment by boratanrikulu** [comment]
Hey.

Thank you for the new feature request.
I will consider about that. For now, it will not be a priority.
