### ISSUE TITLE
Lirik app login bug

### ISSUE THREAD

**Issue by YemreGurses** [boratanrikulu/lirik.app#16]
When I try to login, it gives
"There is no state cookie.
Please do not remove your state cookie." warning. I click refresh and redirects me to the login page. 
![8DF46FFA-0F87-4F48-813A-02BA38248832](https://user-images.githubusercontent.com/33057868/132942283-365a2089-74b6-4c48-8276-d65c5bb9363a.png)

**Comment by boratanrikulu** [comment]
It seems like a ios/safari related bug. Could you try to remove cache for lirik.app on safari?

**Comment by YemreGurses** [comment]
Actually it doesn't work on chrome/ios either. Removed cache on safari and chrome, still not working :(

**Comment by boratanrikulu** [comment]
That's weird actually. I tried with my mobile phone (android) and laptop, with different browsers, seems working well.
I don't have an iOS phone right now, so I'm not able to test it.

**Comment by YemreGurses** [comment]
I removed the lirik app access from apps menu in my spotify account. Then logged in again and it worked. Idk why :)

**Comment by boratanrikulu** [comment]
I think it may re-occur when you close lirik.app and open it. Seems like we have some issues while creating cookies on ios. Let me know if this situation happens.

**Comment by boratanrikulu** [comment]
I removed pwa usage in Lirik.app. The issue should not re-occur when you remove your browser cache.
