### ISSUE TITLE
It should automatically detect song change.

### ISSUE THREAD

**Issue by aykutkardas** [boratanrikulu/lirik.app#2]
Is a socket structure to detect song change possible? It feels bad to have to press a button called "Refresh" for that. @boratanrikulu

**Comment by boratanrikulu** [comment]
Hey,
Thank you for the issue.

Yes, I agree with this situation.
The last time I checked, Spotify doesn't provide Web-Socket [[1]](https://github.com/spotify/web-api/issues/492) or Web-Hook [[2]](https://github.com/spotify/web-api/issues/538).
I didn't want to send repetitive HTTP requests -like every 5 seconds- to Spotify, that's why I just put a button for it.

I will re-check the structure for this issue.

**Comment by aykutkardas** [comment]
Maybe something like this can be done.

```js
window.addEventListener('focus', function(e){
    // spotify request
}
```

**Comment by boratanrikulu** [comment]
Hi again!

I will implement a way in the next few days. Fyi.

**Comment by aykutkardas** [comment]
Good news. 🎉 

If you need my help, I can provide support.

**Comment by boratanrikulu** [comment]
Hi,

@aykutkardas thank you for your cooperation about this issue.

I implemented a way to handle this situation.  
It checks every 2 seconds. I didn't deploy yet. I will.

Example:
![lirik](https://user-images.githubusercontent.com/20258973/103927352-49e32a80-512b-11eb-9ea3-85a8c256bf78.gif)

**Comment by aykutkardas** [comment]
Cool. Maybe it should send requests only if my active tab is _lirik.app_. So it can be more performance.

**Comment by boratanrikulu** [comment]
I have now added checking the active tab too.

I deployed latest version.  
Could you test it? You can check console line too, I didn't remove logs.  
Please logout-login if checking is not started.

**Comment by aykutkardas** [comment]
![image](https://user-images.githubusercontent.com/7966133/103931680-bfea9000-5131-11eb-94af-44240d2877be.png)

Sometimes the song changes in the first area I marked, but the second area is updated on the screen.

Also, even if there is no active tab, I think the "interval" continues to work, but it just doesn't send API requests. Actually in the case of onBlur "interval" should stop. When it is onFocus, you must start it.

It looks more useful now. Congratulations on this enhancement.

**Comment by boratanrikulu** [comment]
~I didn't use interval to avoid memory leaks. I used timeout.~  
~How could I do function to only work on tab active?~

https://github.com/boratanrikulu/lirik.app/pull/7

**Comment by erwinlagu** [comment]
Good News
