### ISSUE TITLE
Lyrics cannot be shown sometimes.

### ISSUE THREAD

**Issue by aykutkardas** [boratanrikulu/lirik.app#3]
![image](https://user-images.githubusercontent.com/7966133/95825098-026e1d80-0d39-11eb-8678-1ac60bd84c0b.png)

--- 

### After 5 times reload (CMD+R)

![image](https://user-images.githubusercontent.com/7966133/95825139-131e9380-0d39-11eb-8654-26d0e6f3dc65.png)

**Comment by boratanrikulu** [comment]
Hi @aykutkardas,

That is occurred cause of some rate limits. 
I've just implemented a structure for server side caching to avoid this situation.  
Current Cache DB is very large, includes a lot of songs. Also, automatically save new songs to cache.

The issue may be occurred again.  
Let me know if it occurs again.
